# Test home page e2e
name: WebPage End-to-End Test

on:
  push:
    branches: cicd
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --save-dev jest babel-jest @babel/core @babel/preset-env puppeteer jest-puppeteer
    - name: E2E test
      run: npm test
