name: Generate Documentation

on:
  push:
    branches:
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build doc
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./source/assets/scripts
          output_dir: ./specs/out

