name: Generate Documentation

on:
  push:
    branches:
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install JSDoc
      run: npm install -g jsdoc
    - name: Build doc
      run: npm run doc  
