name: Generate Documentation

on:
  push:
    branches:
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JSDoc
        run: npm i --save-dev jsdoc
      - name: Build doc
        run: npm run doc
