name: Generate Documentation

on:
  push:
    branches:
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JSDoc
        run: npm i --save-dev jsdoc
      - name: Build doc
        run: npm run doc
      - name: Deploy to Github Pages🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: cicd # The branch the action should deploy to.
          folder: ./specs/docs # The folder the action should deploy
