# Test home page e2e
name: Unit & End-to-End Test

on:
  push:
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --save-dev jest babel-jest @babel/core @babel/preset-env puppeteer jest-puppeteer
    - name: Unit test
      run: npm test ./source/assets/_tests_/unit.test.js
    - name: E2E test
      run: npm test ./source/assets/_tests_/e2e.test.js
