# Unit Test Web Page
name: Unit Test

on:
  push:
    # To avoid checking again after a pull request was approved
    branches-ignore: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --save-dev jest babel-jest @babel/core @babel/preset-env
    - name: Unit test
      run: npm test ./source/assets/_tests_/unit.test.js
